modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="aeaffinity"
version="${version}"
displayName="AE Affinity"
logoFile="logo.png"
authors="Yuzhe"
description='''Lazy server-side storage affinity scheduling for Applied Energistics 2.'''

[[mixins]]
config="aeaffinity.mixins.json"

[[dependencies.aeaffinity]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="SERVER"

[[dependencies.aeaffinity]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="SERVER"

[[dependencies.aeaffinity]]
modId="ae2"
type="required"
versionRange="[19.2,20.0)"
ordering="AFTER"
side="SERVER"
